#!/bin/sh

export QT_QPA_PLATFORM_PLUGIN_PATH="$SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms"
export QT_PLUGIN_PATH="$SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins"
export QML2_IMPORT_PATH="$SNAP/usr/lib/x86_64-linux-gnu/qt5/qml"
export LD_LIBRARY_PATH="$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
export PYTHONPATH="$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH"

exec "$@"
