name: sticky-notes-simple
base: core22
version: '1.0'
summary: A modern sticky notes application with tray icon, pastel themes, and autosave
description: |
  A feature-rich sticky notes application built with PyQt5 that helps you keep track of your notes.
  
  Features:
  - Create, edit, and delete sticky notes
  - Customizable colors and themes (light/dark)
  - Stay on top of other windows
  - System tray integration
  - Multiple workspace support
  - Auto-save functionality
  - Keyboard shortcuts for quick access
  
  Keyboard Shortcuts:
  - Ctrl + N: Create new note
  - Ctrl + H: Hide current note
  - Ctrl + S: Show/Hide notes dialog
  - Ctrl + I: Show information
  
  Developer: Achyutha Krishna Koneti
  Email: achyuth6654@gmail.com
  GitHub: @noob-akk
  
  License: MIT License



grade: stable
confinement: strict

apps:
  sticky-notes-simple:
    command: qt5-launch $SNAP/bin/python3 $SNAP/sticky_notes.py
    desktop: snap/gui/sticky-notes-simple.desktop
    plugs: [desktop, desktop-legacy, x11, wayland, unity7, home]

parts:
  sticky-notes-simple:
    plugin: python
    source: .
    stage-packages:
      - python3-pyqt5
      - python3-pyqt5.qtwebengine
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
      - qt5-gtk-platformtheme
      - libgl1
      - libxkbcommon-x11-0
      - libxcb1
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb1-dev


    python-packages:
      - markdown
    build-packages:
      - python3-dev
    override-build: |
      craftctl default
      cp $CRAFT_PROJECT_DIR/sticky_notes.py $CRAFT_PART_INSTALL/
      cp $CRAFT_PROJECT_DIR/qt5-launch $CRAFT_PART_INSTALL/
